site_name: Kurve docs
#repo_url: https://github.com/kurveai/kurvedocs
#repo_name: kurvedocs
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: switch to dark mode

    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: switch to light mode

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Examples: examples.md

plugins:
  - search
  - git-revision-date-localized
  - autorefs
